### ISSUE TITLE
Ryzen 3000 series support in k10temp

### ISSUE THREAD

**Issue by shmerl** [groeck/k10temp#12] opened 2019-07-15 00:37 UTC
According to multiple reports k10temp doesn't work with Ryzen 3000 series CPUs. Are there any plans to add support for them?

**Comment by groeck** [comment] 2019-07-15 02:20
https://patchwork.kernel.org/patch/11043277/mbox/
https://patchwork.kernel.org/patch/11043271/mbox/

**Comment by mi12078** [comment] 2019-07-24 07:29
A quick question, since I am not so familiar with the linux-staging tree and how/when it gets merged with the main portion of the Linux tree.
I see that the changes are committed after the v5.3-rc1 has been tagged.
Does this mean that these changes will be present in the kernel v5.3, but not prior to that?

**Comment by groeck** [comment] 2019-07-24 09:23
On 7/24/19 12:29 AM, Stefan Maksimovic wrote:
> A quick question, since I am not so familiar with the linux-staging tree and how/when it gets merged with the main portion of the Linux tree.
> I see that the changes are committed after the v5.3-rc1 has been tagged.
> Does this mean that these changes will be present in the kernel v5.3, but not prior to that?
> 

5.4, actually.

Guenter

**Comment by shmerl** [comment] 2019-07-25 05:43
What is a good way to enable it manually for earlier kernels? Just build the k10temp.ko against let's say 5.2.x and replace the one that's installed by default?

**Comment by mi12078** [comment] 2019-07-25 07:03
I just tried it yesterday.
I am running the v5.2.2 arch kernel on top of which I applied the two patches available on hwmon-next,
authored by Marcel Bocu.
The first thing I noticed is that the temps reported are unusually high for my cpu at full load.
I am currently running a Ryzen 3700X, which I am comparing to the Ryzen 1600 I used to run previously.

The temps at idle are nothing out of the ordinary, in my case ~40°C.
At full load (at this time of the year, my ambient temps are ~30°C), the temps were:
- at most ~65°C for the 1600
- at most ~75°C reported for the 3700X

There are reports on the net that some people are complaining about high temps on the Ryzen 3rd gen,
maybe I applied the thermal paste incrorrectly, who knows.

I'll just take this chance to do a comparison between these readings and the one reported by the it87 module which Guenter used to maintain.
Since the repo doesn't exist anymore and hence not maintained, I am not sure whether these readings are correct or not (I assumed that the temp1 reading refers to the cpu, since the value matched the one reported by k10temp at idle).


At idle:
```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +39.8°C  (high = +70.0°C)
Tctl:         +39.8°C
it8655-isa-0290
temp1:        +39.0°C  (low  = -34.0°C, high =  -6.0°C)  ALARM
temp2:        +32.0°C  (low  = -38.0°C, high = +119.0°C)  sensor = disabled
temp3:        +35.0°C  (low  = +107.0°C, high = +116.0°C)  sensor = thermistor
```

Loaded:
```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +73.8°C  (high = +70.0°C)
Tctl:         +73.8°C
it8655-isa-0290
temp1:        +58.0°C  (low  = -34.0°C, high =  -6.0°C)  ALARM
temp2:        +33.0°C  (low  = -38.0°C, high = +119.0°C)  sensor = thermistor
temp3:        +48.0°C  (low  = +107.0°C, high = +116.0°C)  sensor = thermistor
```
I'd appreciate if someone else could report their temperatures for comparison (I'm not sure whether this is the appropriate place for it though, sorry for the noise if it isn't).

**Comment by groeck** [comment] 2019-07-25 13:15
On 7/25/19 12:03 AM, Stefan Maksimovic wrote:
> I just tried it yesterday.
> I am running the v5.2.2 arch kernel on top of which I applied the two patches available on hwmon-next,
> authored by Marcel Bocu.
> The first thing I noticed is that the temps reported are unusually high for my cpu at full load.
> I am currently running a Ryzen 3700X, which I am comparing to the Ryzen 1600 I used to run previously.
> 
> The temps at idle are nothing out of the ordinary, in my case ~40°C.
> At full load (at this time of the year, my ambient temps are ~30°C), the temps were:
> 
>   * at most ~65°C for the 1600
>   * at most ~75°C reported for the 3700X
> 

AFAIK that is as expected. Actually, one of my 3900X runs up to 95C when compiling the kernel,
but that is in a small chassis with inadequate cooling.

Guenter

**Comment by groeck** [comment] 2019-07-25 13:17
On 7/24/19 10:43 PM, shmerl wrote:
> What is a good way to enable it manually for earlier kernels? Just build the k10temp.ko against let's say 5.2.x and replace the one that's installed by default?
> 

Not really. Adding support for the chip requires some changes elsewhere in the kernel.

Guenter

**Comment by wezm** [comment] 2019-07-25 21:59
> I'd appreciate if someone else could report their temperatures for comparison (I'm not sure whether this is the appropriate place for it though, sorry for the noise if it isn't).

I built a custom kernel with the patches applied (also based on the 5.2.2 Arch kernel). My temps are:

Relatively idle:

```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +47.8°C  (high = +70.0°C)
Tctl:         +47.8°C
```

Compiling code with all cores busy:

```
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +81.6°C  (high = +70.0°C)
Tctl:         +81.6°C
```

The reading are very jumpy though, almost instantly jumping to 80 before dropping down 5, or 10 degrees a few seconds later.

**Comment by groeck** [comment] 2019-07-25 22:15
I see a more gradual temperature increase, at least relatively speaking. On one of my systems, it takes some 10 seconds for the chip to reach 80°C when compiling the kernel. On another, with better cooling, it takes some 25 seconds to get to the same temperature. Both is with 3900X. It is quite likely that this depends on motherboard settings, and an excellent thermal connection between CPU and cooler seems to be very important.

**Comment by wezm** [comment] 2019-07-25 22:35
I tweaked my CPU fan profile to be a bit more aggressive and compiling the kernel the temperatures ramped up a lot more gradually from 70 to 80 degress

**Comment by zocker-160** [comment] 2019-07-26 13:53
> I'd appreciate if someone else could report their temperatures for comparison (I'm not sure whether this is the appropriate place for it though, sorry for the noise if it isn't).

@mi12078 I guess it is OT but my 3700X @3,9-4,0GHz is hovering around 60-65°C (room temp is 27-30°C - yeah very hot...) running an all core blender render
CPU cooler is a Dark Rock Pro 4

most important is to have a CPU cooler that cools the bottom right (and left for the 3900X) very good, many AIOs, that mostly cool only the middle of the chip, are not optimal

**Comment by groeck** [comment] 2019-07-27 19:46
After replacing the stock cooler with a FUMA 2 and using MX-4 thermal compound, the temperature in my larger system no longer rises above 78C. SIngle core boost (as observed during normal operation) is now above 4.4 GHz, and all cores now run at 4.05-4.1 GHz under full load (previously they dropped below 4 GHz). Conclusion: A good cooling solution is absolutely essential.

**Comment by shmerl** [comment] 2019-07-28 06:26
Is there any recommended way to apply the thermal paste on Ryzen 9 3900X? I've seen many mentioned, that chiplet design makes common pea-sized method to be not very efficient. I plan to use Noctua NH-D15 SE-AM4 which should be a good cooler, but thermal paste application method can play a role.

**Comment by groeck** [comment] 2019-07-28 13:38
How to apply thermal paste: No idea. I always spread it manually before attaching the cooler, as I never trusted the "pea-sized" method.

**Comment by karolgrudzinski** [comment] 2019-08-01 09:34
Pea-sized method is good for CPUs where cores are in the middle of a die. In Ryzen 3000 cores are moved to a side [1] so spreading manually may give a much better results. But overall applying method [2] and amount of thermal paste [3] doesn't really matter.

[1] https://youtu.be/WXbCdGENp5I?t=612
[2] https://youtu.be/nWu2tcm4wL8?t=922
[3] https://www.youtube.com/watch?v=EUWVVTY63hc

**Comment by shmerl** [comment] 2019-08-04 08:15
> Adding support for the chip requires some changes elsewhere in the kernel.

Would it work with 5.3.x if patches are applied, or only with later ones?

**Comment by groeck** [comment] 2019-08-04 13:39
Sure, if the relevant patches are applied. However, give the latest driver here a try.

**Comment by KeithMyers** [comment] 2019-08-04 18:38
I think I missed an important part.  The module here won't work unless you have the latest 5.4 kernel? I made the module here and installed it but it obviously isn't working on my Ubuntu 18.04.2 LTS with kernel 4.15.0-56-generic.
keith@Serenity:~$ sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tdie: +206.9°C (high = +70.0°C)
Tctl: +206.9°C

**Comment by shmerl** [comment] 2019-08-04 18:50
Still waiting for the motherboard, but I'll test it soon after I'll finish my build.

By the way, the last commit in this repo is different from current state in Linux-next https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/drivers/hwmon/k10temp.c

**Comment by vincentkfu** [comment] 2019-08-04 19:15
I have k10temp working for Ubuntu 18.04 here: https://github.com/vincentkfu/k10temp. Using the latest driver here gives me the same output as @KeithMyers

**Comment by groeck** [comment] 2019-08-04 20:55
Yes, @vincentkfu's version works because it doesn't take multi-die chips into account. That gives me an idea how to handle it. Stay tuned ...

**Comment by KeithMyers** [comment] 2019-08-04 22:14
I take that comment that @vincentkfu's version won't work for multi-die cpus like my 3900X?

**Comment by groeck** [comment] 2019-08-04 22:30
@KeithMyers : Oh, it does. The temperature sensor is in the io block, and the 3900X has only one of those. The problem only affects Threadripper and the server CPUs.
[ But, of course, if you happen to dislike your 3900X because of that, I'll be happy to take that burden off you. Just send it to me :-) ]

**Comment by groeck** [comment] 2019-08-05 00:41
Would be great if someone can give the current version a try.

**Comment by KeithMyers** [comment] 2019-08-05 01:54
Sorry, I am just back after tearing down the computer once again to do a supposedly absolutely BIOS UEFI clearance to fix the Auto voltage and all the fan headers suddenly outputting 0 volts.  No change.

Anyway, yes your latest https://github.com/groeck/k10temp/commit/63e3482738f28f79b0aaee38d3c6a9622c91a83e commit works now.  This is sensors now with a proper k10temp output.
`keith@Serenity:~$ sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

asuswmisensors-isa-0000
Adapter: ISA adapter
CPU Core Voltage:         +1.27 V  
CPU SOC Voltage:          +1.09 V  
DRAM Voltage:             +1.41 V  
VDDP Voltage:             +0.22 V  
1.8V PLL Voltage:         +1.83 V  
+12V Voltage:            +12.10 V  
+5V Voltage:              +4.96 V  
3VSB Voltage:             +3.33 V  
VBAT Voltage:             +3.27 V  
AVCC3 Voltage:            +3.36 V  
SB 1.05V Voltage:         +1.11 V  
CPU Core Voltage:         +1.28 V  
CPU SOC Voltage:          +1.09 V  
DRAM Voltage:             +1.42 V  
CPU Fan:                 2020 RPM
Chassis Fan 1:           1229 RPM
Chassis Fan 2:            698 RPM
Chassis Fan 3:            991 RPM
HAMP Fan:                   0 RPM
Water Pump:                 0 RPM
CPU OPT:                 6015 RPM
Water Flow:                 0 RPM
AIO Pump:                1872 RPM
CPU Temperature:          +39.0°C  
CPU Socket Temperature:   +29.0°C  
Motherboard Temperature:  +29.0°C  
Chipset Temperature:      +43.0°C  
Tsensor 1 Temperature:    +27.0°C  
CPU VRM Temperature:      +34.0°C  
Water In:                +216.0°C  
Water Out:               +216.0°C  
CPU VRM Output Current:  +10.00 A  

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +38.0°C  (high = +70.0°C)
Tctl:         +38.0°C`

**Comment by shmerl** [comment] 2019-08-05 01:55
@KeithMyers: how exactly did you install it, just built .ko and replaced the default one with it?

**Comment by KeithMyers** [comment] 2019-08-05 02:42
Yes, just sudo make and sudo make install. Added k10temp to /etc/modules-load.d/modules.conf. Reboot and !voila!

**Comment by shmerl** [comment] 2019-08-05 03:01
@KeithMyers: a bit unrelated, but are you able to see X570 chipset fan rotation speed?

**Comment by KeithMyers** [comment] 2019-08-05 03:37
As far as I know all the board manufacturers dropped ITE sensors for X570 boards and went with Nuvoton SIO chips.  The driver for those chipsets are the NCT6775 driver.  That driver has been pretty stable for a long time.  Doesn't report as much as the asus-wmi-sensor driver, but enough.  Less issues too though have to add acpi_enforce_resources=lax to your kernel command line in the grub file to get the driver to load.

**Comment by groeck** [comment] 2019-08-05 03:51
Great, looks like the problem is fixed. Closing.
On a side note, Nuvoton is much easier to work with than ITE. They are happy to provide datasheets when asked, unless a board vendor insists on a mutual NDA and prevents them from providing it. ITE doesn't provide anything. Board vendors are all a PITA to work with - if they respond at all, it is usually "we don't support Linux".

**Closed by groeck** 2019-08-05 03:51 UTC

**Comment by vincentkfu** [comment] 2019-08-05 11:25
Now working for me as well.
@shmerl @KeithMyers to avoid having to reboot you can run
`modprobe -r k10temp && modprobe k10temp`
after you have installed your newly compiled kernel module.

**Comment by mixedCase** [comment] 2019-08-14 05:23
First of all, thanks for your work Mr. Roeck, k10temp is working beautifully over here on a 3900x, showing me that clearly this needs an aftermarket fan or be watercooled if I want to run make -j24 on a large project.

As for @KeithMyers, regarding your mobo sensor, this machine is running on a Gigabyte Aorus Master and sensors-detect was able to pick up an it8792, so at least Gigabyte seems to still be using ITE for X570.

**Comment by KeithMyers** [comment] 2019-08-14 06:24
Thanks for the note.  All the previous info I had seen was that for the majority of the mobo vendors, they had dropped the problematic ITE SIO chips and gone for tried and true, tested Nuvoton SIO solutions.

Have you been able to use the old it87 code branch on that SIO? At least k10temp works.

**Comment by mixedCase** [comment] 2019-08-14 14:05
@KeithMyers Yes, this is with whatever's shipping in 5.3-rc3 mainline.

**Comment by groeck** [comment] 2019-08-14 22:16
> As for @KeithMyers, regarding your mobo sensor, this machine is running on a Gigabyte Aorus Master and sensors-detect was able to pick up an it8792, so at least Gigabyte seems to still be using ITE for X570.

Same for Gigabyte B450 AORUS M

**Comment by groeck** [comment] 2019-08-14 22:25
> First of all, thanks for your work Mr. Roeck, k10temp is working beautifully over here on a 3900x, showing me that clearly this needs an aftermarket fan or be watercooled if I want to run make -j24 on a large project.

I think that depends on the individual chip. I have three of them now. Two run fine with Scythe Fuma 2 and Scythe Big Shuriken 3, and even better after I replaced the fans with Noctua fans. The third, with Scythe Big Shuriken 3, runs a bit hot (90-92C @ full load), but for a 2RU chassis that is still pretty good. I would not recommend using the stock cooler for heavy loaded systems.

**Comment by shmerl** [comment] 2019-09-04 04:19
Trying to build kernel 5.3-rc7 now using `make -j 23` on Ryzen 9 3900X with the patches for k10temp. So far I'm measuring the temperature through SMBUSMASTER 1

Periodically temperature jumps above 70°C and then the system reboots. Is it kernel doing it, or motherboard firmware? I have a pretty beefy cooler (Noctua NH D15).

**Comment by KeithMyers** [comment] 2019-09-04 04:39
I was overtemp rebooting at 78° C.  A lot further from the published 95°C. spec.  Probably all the changes in the AGESA code.

**Comment by shmerl** [comment] 2019-09-04 04:41
Yeah, 78°C could be it. Does it mean I need a more aggressive fan profile and AMD don't want anything above that for a reason, or it's a bug in AGESA or UEFI?

**Comment by groeck** [comment] 2019-09-04 12:20
A temperature below 80C should not cause a reboot. One of my 3900X heats up to 93C (in a low profile chassis), without impact on stability. If that happens, it just slows down on its own. Also, in a system with proper cooling, such as with the mentioned Noctua cooler, it should not get up to 90C in the first place. Something else is wrong in your system.

**Comment by shmerl** [comment] 2019-09-04 15:11
I don't think it's hitting 90°C in my case. It reboots somewhere below 80°C. My only overclock is running RAM at 3600 MHz (using XMP profile). I didn't touch any CPU overclocking settings.

That said, some claim that Asrock do some hidden overclocking with X570 Taichi even if you don't set that explicitly. I'll need to investigate this further.

**Comment by groeck** [comment] 2019-09-04 15:24
That really suggests that somethng is wrong either with your board or with your cpu. I have four systems with 3900x. Three are in 2RU chassis and run hotter than 90C under load. The 4th is in a large chassis with better cooling and gets up to ~80C under load. All systems run perfectly stable. My motherboards are all with B450.

**Comment by shmerl** [comment] 2019-09-04 16:56
@KeithMyers : what are your values for:

```/sys/devices/virtual/thermal/thermal_zone0/trip_point_*_temp```

I'll check mine later (not at that computer now), but some suggest that if they are buggy (too low) due to ACPI misdetection, Linux itself can reboot at those thresholds. Not sure if that's correct.

**Comment by groeck** [comment] 2019-09-04 17:08
On Wed, Sep 04, 2019 at 09:56:20AM -0700, shmerl wrote:
> @KeithMyers : what are your values for:
> 
> ```/sys/devices/virtual/thermal/thermal_zone0/trip_point_*_temp```
> 
> I'll check mine later (not at that computer now), but some suggest that if they are buggy (too low) due to ACPI misdetection, Linux itself can reboot at those thresholds. Not sure if that's correct.
> 
FWIW, I have ACPI_THERMAL enabled in my configuration,
but I don't see any thermal zones, only cooling devices.
And those point to the CPUs.

Guenter

**Comment by KeithMyers** [comment] 2019-09-04 18:02
> FWIW, I have ACPI_THERMAL enabled in my configuration,
but I don't see any thermal zones, only cooling devices.
And those point to the CPUs.
> 
I don't have ACPI_THERMAL in my configuration but I too don't have any thermal_zones.  Only cooling_devices.  No trip_point files.

The recent AGESA 1.0.0.3 ABB dropped the fan temp trip to 75° C. At that point all fans go to 100% speed.

I have custom cooling loop on my 3900X.  But if the fans don't run there is no heat exchange taking place and the cpu overtemps.  There is a bug in the BIOS that disables the fan headers sporadically.  That is what caused by overtemp conditions.  I have since removed all fans from the motherboard headers and plugged them into a standalone fan controller.  Problem solved.  Still waiting on the Beta 0002 BIOS with the fixed fan header issue to make it to an official BIOS.

I have the ASUS Crosshair VII Hero motherboard.

**Comment by shmerl** [comment] 2019-09-04 18:09
Does it mean everyone with that AGESA should be affected? Many report they don't have such issue. Or it only manifests on specific motherboard?

**Comment by groeck** [comment] 2019-09-04 20:58
The AGESA version on my boards is ComboPI 1.0.0.3ab (MSI) and 1.0.0.3 ABB (Gigabyte). My boards are MSI B450 Tomahawk, MSI B450M Mortar Titanium, and Gigabyte B450 Aorus M. I don't see any problems.

**Comment by shmerl** [comment] 2019-09-04 21:04
@KeithMyers: did Asus acknowledge such bug? Some posts about it would be helpful, to direct Asrock support to them.

**Comment by KeithMyers** [comment] 2019-09-04 21:57
There are plenty of posts about the bug in the BIOS at the OCN Crosshair VII Hero overclocking thread. And in the ROG Crosshair forums where Shamino who is on the BIOS development team posted links to the 0002 Beta BIOS that fixed the fan issue.
[https://www.overclock.net/forum/11-amd-motherboards/1685809-rog-crosshair-vii-overclocking-thread-post28113398.html?highlight=fans+stopping#post28113398](url)
[https://rog.asus.com/forum/showthread.php?112744-Crosshair-VI-Wifi-fan-control-sensors-are-broken](url)

**Comment by KeithMyers** [comment] 2019-09-04 22:10
Mumak, the developer of the HwInfo64 monitoring app pretty much lays the blame on ASUS.  They had this WMI interface problem before and fixed it on the previous non Combi-PI BIOS', but reintroduced  the issue in the current Combi-Pi BIOS's and need to squash the bugs again.  This problem only occurs on the boards that have the WMI interface in the BIOS.

**Comment by shmerl** [comment] 2019-09-04 23:07
Just check my setup, and I see this:

```ls -la /sys/devices/virtual/thermal/thermal_zone0/trip_point_*_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_1_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_2_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_5_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_6_temp
-rw-r--r-- 1 root root 4096 Sep  4 19:06 /sys/devices/virtual/thermal/thermal_zone0/trip_point_7_temp```

```cat /sys/devices/virtual/thermal/thermal_zone0/trip_point_*_temp
-32768000
-32768000
-32768000
-32768000
-32768000
-32768000
-32768000
-32768000```

What exactly are those values? -32768000 looks weird.

**Comment by shmerl** [comment] 2019-09-04 23:41
Just run one test. Lowered RAM frequency to auto (1866 MHz). It's not rebooting, and temperature doesn't go above 71°C.

Set XMP profile to 3600 MHz/CL16 and it rebooted at around 72.5°C. I'll run separate RAM tests, could be this is just some defective RAM.

**Comment by groeck** [comment] 2019-09-05 00:15
I _did_ have issues with 2700X when clocking the memory too high, so a RAM problem may well exist. I would suggest to clock it a bit lower than 3600; maybe start with 3200 and see if it is stable.
-32768000 is equivalent to ((short)0x8000) * 1000, so I would guess that ACPI reports some nonsense temperature limits to Linux. I would guess another BIOS problem.

**Comment by KeithMyers** [comment] 2019-09-05 00:38
I like the new stable RAM clocks available on my 3900X.  I ran the 3533CL14 profile as soon as I got the cpu.  An improvement over the stable  3466CL14 profile I ran on my 2700X.

I am on a stable 3600CL14 profile now for the 3900X.  Marginal improvement in Geekbench4 scores over the previous 3533CL14 tests.  I don't see much if any improvement in my crunching times with the higher memory clocks.  Desktop might seem a bit snappier, but likely just a placebo effect.

**Comment by shmerl** [comment] 2019-09-05 00:43
I was also using stable node and XMP for 3600/CL16, but apparently it's not stable enough :) Could be CPU itself has a bad memory controller, or motherboard isn't setting things well.

**Comment by KeithMyers** [comment] 2019-09-05 01:21
Other than the special Stilt memory presets for Samsung B-die memory that are in my BIOS, I have never used the stock memory settings.  The motherboard gets it wrong too many times.  I depend on using 1usmus's RAM Calculator for Ryzen.  It works every time.  If the memory is GSAT stable for even 15 minutes, I know it will run 24/7 for my normal BOINC loading.  Same goes for my cpu clocks, I test with Prime95 small FFT's and if it doesn't drop a thread after 30 minutes, I know the cpu clocks are stable with my BOINC load.

If you haven't downloaded the Calculator, do yourself a favor and do so.  Covers Samsung, Micron and Hynix memory types on Ryzen 1, 1+, Ryzen 2 and Threadripper platforms.  X370/X470 and X570 chipsets settings.

[https://www.overclock.net/forum/13-amd-general/1640919-new-dram-calculator-ryzena-1-6-1-overclocking-dram-am4-membench-0-8-dram-bench.html](url)

**Comment by shmerl** [comment] 2019-09-05 01:31
@KeithMyers: How do you read the info to feed to the calculator? The video on that page references some Thaiphoon tool, which is Windows only.

**Comment by shmerl** [comment] 2019-09-05 01:57
OK, managed to the calculator in Wine (takes some time to set up all the .NET stuff), but it asks for something called "Profile version" and rank. I can see rank in `dmidecode -t memory`, but not sure about profile version.

**Comment by KeithMyers** [comment] 2019-09-05 02:18
You don't Thaiphoon Burner anymore to feed in timings.  All that is necessary is to determine which type of memory chips your sticks use.  If you know the type of memory you have, you choose from the picklist.  Maybe your memory is common and others using Windows have determined the memory dies.  I never had to use Thaiphoon Burner because all my memory is Samsung B-die.  Made a point of only buying the best memory available for Ryzen.  I just select Samsung B-die, single rank and my desired memory clocks I want to use.  Then select the R-XMP button and then the FAST or the SAFE buttons.

What is the model number and brand of your memory and the XMP ratings as sold?

**Comment by shmerl** [comment] 2019-09-05 02:20
Mine is Samsung B-die, so I'll use that. For some reason dmidecode shows rank as 1, but I think mine is dual rank?

That's my RAM: http://www.gskill.com/specification/165/168/1536288991/F4-3600C16Q-32GTZKK-Specification

**Comment by KeithMyers** [comment] 2019-09-05 02:30
Rank is either single or dual rank.  8GB sticks are always single rank.  16GB sticks are dual rank.  Some sticks have 1 or 2 XMP profiles stored in the memory.  Use V1 profile for the most relaxed.  BCLK is standard 100Mhz for Ryzen unless your are overclocking by raising BCLK.

No your memory is definitely Samsung B-die. Single rank.  What motherboard are you using?  Do you know if you have a X370 or X470 chipset?  Select the appropriate.  Then click the R-XMP button to fill in the timings in ns.  Then select the Safe or the Fast button.   Fast settings are tightened up considerably for performance.  Then look at the recommended Vram voltage to use.  Then go into the BIOS and enter the primary and secondary timings for your desired clock. Make sure you select 4 sticks in the settings.

4 sticks are harder for the cpu IMC to drive, so I would probably start with 3466CL14 Safe and see if that is stable.  Then try Fast and then go up the ladder to your 3600 CL16 settings.

Doesn't matter.  All Ryzen motherboards are dual channel. Only Threadripper motherboards are quad channel.

Pay attention to the actual labels for the memory parameters.  The tRDCRD parameter is out of order from the Calculator's list.  That trips people up a lot.  Other than that one parameter, I can just go down the list and enter the suggested values right down the BIOS settings.  At leas for my ASUS C7H board.

**Comment by shmerl** [comment] 2019-09-05 02:37
OK, here is what I got (using safe preset). I'll give it a try:

![ram](https://user-images.githubusercontent.com/310927/64307598-9b423f00-cf64-11e9-9347-5819ba1374a2.png)

**Comment by shmerl** [comment] 2019-09-05 03:09
Nope, the above is causing random system freezing, so timings aren't right apparently. A bit strange it made it 16-16-16-32, while the RAM is listed as 16-16-16-36.

**Comment by KeithMyers** [comment] 2019-09-05 03:32
Voltage is incorrect.  The XMP ratings for that memory is 1.35V minimum  B-die likes voltage.  Up to 1.5V is safe is the memory temps are kept under 45°C.

I would set the memory for at least 1.4V.  If your BIOS has a boot Vram voltage, make sure to set it also at minimum of 1.35V

**Comment by KeithMyers** [comment] 2019-09-05 03:40
I'll have to post to the Calculator thread your screenshot.  The settings for Vram voltage are incorrect.  Looks like a typo. An extra leading 1 in front of the important part.

Try the Fast settings and look at the recommended voltages.  I bet they are showing 1.4 for the voltages.  My 3600 Fast settings are 1.44V min. 1.450 recommended and 1.480 max for my B-die.

**Comment by shmerl** [comment] 2019-09-05 03:44
I actually didn't touch the voltages.

**Comment by KeithMyers** [comment] 2019-09-05 03:46
I just posted your calculator screenshot to the OCN thread for 1usmus. Put the memory voltage to 1.44 to start.

**Comment by KeithMyers** [comment] 2019-09-05 03:47
1.35V is inadequate for B-die unless running at 3200 or lower.

**Comment by shmerl** [comment] 2019-09-05 03:47
So how are they listing it as 1.35V for 3600?

http://www.gskill.com/specification/165/168/1536288991/F4-3600C16Q-32GTZKK-Specification

**Comment by KeithMyers** [comment] 2019-09-05 03:48
That is what the have to list for an XMP rating.  Doesn't mean it has to run at that voltage.  Mfr's bend the truth to sell products.

**Comment by shmerl** [comment] 2019-09-05 04:14
Still rebooting even with 1.44 V for RAM voltage. May be RAM is defective, or the CPU memory controller?

**Comment by shmerl** [comment] 2019-09-05 15:37
Jut FYI. I set frequency to 3200 MHz (keeping the rest of the settings from 3600 MHz profile, which is probably not optimal) and it didn't reboot. Built the whole kernel with temperature hovering slightly above 75°C. So I don't think it's a thermal issue, something must be with memory controller or RAM itself. I'll dig deeper may be making a post on Overclockers.net to get more feedback.

**Comment by KeithMyers** [comment] 2019-09-05 16:55
Pull the memory out and reseat the sticks. If you can get 3200 to stay alive long enough to compile the kernel, then run GSAT Google Stress App test for at least 15 minutes.  Preferably for an hour.
`sudo apt install stressapptest`
Then run for 15 minutes testing 93% of your 32GB
`stressapptest -W -M 30474 -s 900 --pause_on_delay 300`
Change to 3600 for s time variable to run for an hour (3600 seconds)  The pause on delay  drops the threads every 5 minutes to power spike the memory and controller to try and upset it.

It you have no hardware failures at the end of the test, the memory is stable at your settings and something else is causing the reboot.  A grossly misconfigured memory subsystem will usually throw an error in the first minute.  Then go back to the BIOS and loosen timings up or increase the Vram voltage.

**Comment by groeck** [comment] 2019-09-05 16:59
Do you mean --pause_delay ? --pause_on_delay does not exist in the version of stressapptest I have installed.

**Comment by KeithMyers** [comment] 2019-09-05 17:02
Yes, I goofed.  --pause_delay is the correct parameter.

**Comment by shmerl** [comment] 2019-09-08 04:13
OK, I run stressapptest and it caused a reboot. Does it mean the RAM can be defective? It's not very conclusive. I.e. what if CPU's memory controller simply can't handle it at that frequency?

**Comment by KeithMyers** [comment] 2019-09-08 04:29
Or the timings and other parameters still aren't correct for your desired clock speed. Resistances on the bus are also very important. ProcODT and the RTT bus resistances are very important to damp down reflections on the bus.  Have you tried setting Gear Down Mode on?  The CAD bus resistances are important also.

**Comment by KeithMyers** [comment] 2019-09-08 04:30
It would have to be the most defective and bottom of the barrel binned IMC in a cpu that can't handle 3200Mhz.

**Comment by shmerl** [comment] 2019-09-08 04:34
It works at 3200 MHz, I meant it can't handle 3600. I set resistances and etc. using DRAM calc. So far playing around with SOC voltages and VDDG / VDDP. Something fishy is going on with the motherboard, sometimes they get reset even after I set them.

**Comment by KeithMyers** [comment] 2019-09-08 04:40
Every BIOS on my ASUS C7H up to the latest 2703 was flaky, and I could not change any memory parameter or I would get a C5 BIOS error code which forced and CMOS reset every time I wanted to change any memory parameter.  Only this latest AGESA 1.0.0.3 ABB 2703 BIOS allows me to change cpu clocks, memory clocks or voltages with one cycle of memory training that boots directly to my OS with no issues.  Major improvement on the previous BIOS'

**Comment by KeithMyers** [comment] 2019-09-08 04:41
So settle for 3533 CL14 instead of 3600Mhz.  Still would faster than 3600CL16.

**Comment by shmerl** [comment] 2019-09-08 04:54
Oh, now I got something interesting in the test:

```
Log: CrcWarmCopyPage CRC mismatch 5e9f7fffa25eaaaaaa4c230aca2a88172311aaaa8799 != ffffffff01ffffffff011002aaaa9ac801002aaaa9ac80, but no miscompares found. Retrying with fresh data.
Report Error: miscompare : DIMM Unknown : 1 : 33s
Hardware Error: miscompare on CPU 18(0x80) at 0x7fe33b6ffa10(0x0:DIMM Unknown): read:0x3ff9435e60000000, reread:0x3ff9435e60000000 expected:0xaaaaaaaaaaaaaaaa
Report Error: miscompare : DIMM Unknown : 1 : 33s
Hardware Error: miscompare on CPU 18(0x80) at 0x7fe33b6ffa18(0x0:DIMM Unknown): read:0x0000000000000000, reread:0x0000000000000000 expected:0xaaaaaaaaaaaaaaaa
```

**Comment by shmerl** [comment] 2019-09-08 08:53
That's interesting. I used settings from DRAM calculator and only increased RAM voltage to 1.4V. And it's not rebooting anymore, built the whole kernel!

stressapptest gets stuck though, after that pausing step:
```
Log: Pausing worker threads in preparation for power spike (600 seconds remaining)
Log: Seconds remaining: 590
Log: Resuming worker threads to cause a power spike (585 seconds remaining)
```
And it just hangs, but no errors like before.

**Comment by groeck** [comment] 2019-09-08 14:34
On Sun, Sep 08, 2019 at 01:53:02AM -0700, shmerl wrote:
> That's interesting. I used settings from DRAM calculator and only increased RAM voltage to 1.4V. And it's not rebooting anymore, built the whole kernel!
> 
> stressapptest gets stuck though, after that pausing step:
> ```
> Log: Pausing worker threads in preparation for power spike (600 seconds remaining)
> Log: Seconds remaining: 590
> Log: Resuming worker threads to cause a power spike (585 seconds remaining)
> ```
> And it just hangs, but no errors like before.
> 
Same happened to me when I tried. I wonder if it is a bug in stressapptest.

Guenter

**Comment by KeithMyers** [comment] 2019-09-08 15:17
It is not a bug with stressapptest, or I don't think it is.  It is the way the Terminal handles the output from GSAT on Ubuntu 18.04.  The test continues to run  to the end if you let it and don't stop it.  It then prints the normal output.  On Ubuntu 19.04, it runs all the way through to the end continuing to output after the pause_delay and prints the output all the way through.  Something is different in the Display Managers handling of Terminal.

@shmerl What did I tell you about Sammy B-die liking voltage.  Just run it at 1.4V

**Comment by shmerl** [comment] 2019-09-08 15:25
Hm, for me in Kosnole it just continued running, and never stopped even after 15 minutes, so I had to `kill -9` it.

Yep, apparently even slightly increasing voltage made it stable. Running it now at 1.362 V and it's OK.

**Comment by dendisuhubdy** [comment] 2021-07-03 06:28
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A

nouveau-pci-2100
Adapter: PCI adapter
temp1:        +39.0°C  (high = +95.0°C, hyst =  +3.0°C)
                       (crit = +122.0°C, hyst =  +2.0°C)
                       (emerg = +135.0°C, hyst =  +5.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +16.8°C  (crit = +20.8°C)

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +94.9°C  (high = +70.0°C)
Tctl:         +94.9°C

enp69s0-pci-4500
Adapter: PCI adapter
PHY Temperature:  +42.0°C
```
